version: "3.8"
services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/
    environment:
      POSTGRES_USER: "postgresuser"
      POSTGRES_PASSWORD: "Passw0rd"
      POSTGRES_DB: "postgres"
  volumes:
    db_volume: