version: "3.8"
services:
  postgresdb:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-volume:/var/lib/posgresql/data
    environment:
      POSTGRES_USER: "postgresuser"
      POSTGRES_PASSWORD: "Passw0rd"
      POSTGRES_DB: "postgres"

  userapi:
    image: userapi:latest
    restart: always
    depends_on: 
      - "postgresdb"
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8000:80

volumes:
  db-volume: